name: dnddmcompanion
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.1
  provider: ^6.0.2
  flutter_riverpod: ^1.0.3
  path_provider: ^2.1.3
  file_picker: ^8.0.3
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/images/
    - assets/images/maps/
    - assets/images/playerIcons/
    - assets/images/enemyIcons/
